baseURL = "https://twiddlingbits.net/"
languageCode = "en-us"
title = "twiddling bits"

theme = "harbor"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[author]
name = "James Reed"

[[params.nav]]
identifier = "about"
name = "about"
icon = "fas fa-user fa-lg"
url = "/about/"
weight = 1

[[params.nav]]
identifier = "categories"
name = "categories"
icon = "fas fa-folder-open fa-lg"
url = "categories"
weight = 2

[[params.nav]]
identifier = "tags"
name = "tags"
icon = "fas fa-tag fa-lg"
url = "tags"
weight = 3

[[params.social]]
name="github"
url="https://github.com/jcrd"
icon="fab fa-github fa-lg"

[params.logo]
url = "icon.png"
width = 40
height = 40
alt = "logo"

[permalinks]
posts = "/:title/"
