baseURL: "https://twiddlingbits.net"
languageCode: "en-us"
title: "twiddling bits"

module:
  imports:
    - path: lessen

enableInlineShortcodes: true
pygmentsCodeFences: true
pygmentsUseClasses: true

frontmatter:
  lastmod:
    - lastmod
    - date
    - publishDate

disableKinds:
  - taxonomy
  - term

build:
  writeStats: true

author:
  name: "James Reed"

params:
  description: "bits of blogging"
  highlight: true
  analytics:
    goatcounter: "twiddlingbits.goatcounter.com"

permalinks:
  posts: "/:title/"
