baseURL = "https://twiddlingbits.net/"
languageCode = "en-us"
title = "twiddling bits"

theme = "readme"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[build]
writeStats = true

[params]
description = "bits of blogging"
author = "James Reed"
highlight = true

[params.analytics]
goatcounter = "twiddlingbits.goatcounter.com"

[[menu.main]]
identifier = "about"
name = "about"
url = "/about"
weight = 1

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 3

[permalinks]
posts = "/:title/"
