FROM supplantr/toolbox

ARG HUGO_VERSION=0.88.1

RUN wget -O hugo.tar.gz \
    https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz && \
    tar -xzf hugo.tar.gz && \
    cp -p hugo /usr/bin/hugo
