name: github pages devel

on:
  push:
    branches:
      - devel

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages-devel
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "npm"

      - run: npm ci
      - run: npm run build
        env:
          ELEVENTY_ENV: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages-devel
